# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  welcome-server:
    build:
      context: ./app
    links:
      - welcome-mongo
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  welcome-mongo:
    image: mongo
    container_name: mongo
    #volumes: 
    #  - database:/data/db
    ports:
      - "27017:27017"

#volumes:
  #database: